spring:
   profiles:
      active: "development"
   jpa:
       show-sql: false
       database: mysql
       properties:
           hibernate:
             dialect: org.hibernate.dialect.MySQL5InnoDBDialect
             ddl-auto: create-drop
             show_sql: true
             hbm2ddl:
               import_files:

   datasource:
       url: jdbc:mysql://192.168.99.100:3306/proojec
       username: root
       password: Irl4nd42014
       driver-class-name: com.mysql.jdbc.Driver

auth0:
  domain: proojec.eu.auth0.com
  issuer: https://proojec.eu.auth0.com/api/v2/
  clientId: BZPVxMgjhec3SjeGb7MOeetZnmQNfkqF
  clientSecret: Xok4lqMUc53slE33-MsJVhVTQrsI0mjBiuBFpmBCHKXwq2iG3B5PtYTy6Wj0mBQo
  onLogoutRedirectTo: /login
  loginCallback: /callback
  apiAudience: Auth0 Management API

---

spring:
  profiles: development
  jpa:
    generate-ddl: true
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
      url: jdbc:mysql://192.168.99.100:3306/proojec
      username: root
      password: Irl4nd42014

---

spring:
  profiles: production
  jpa:
    generate-ddl: false
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
      url: jdbc:mysql://localhost:3306/proojec
      username: wordpress
      password: Irl4nd42014