spring:
   jackson.serialization:
      write_dates_as_timestamps: false
   application:
      name: proojec
   main:
      banner-mode: "log"
   profiles:
      active: "development"
   jpa:
       show-sql: false
       database: mysql
       properties:
           hibernate:
             dialect: org.hibernate.dialect.MySQL5InnoDBDialect
             ddl-auto: create-drop
             show_sql: true
             hbm2ddl:
               import_files:

   datasource:
       url: jdbc:mysql://192.168.99.101:3306/proojec
       username: root
       password: Irl4nd42014
       driver-class-name: com.mysql.jdbc.Driver

auth0:
  issuer: https://proojec.eu.auth0.com/
  apiAudience: http://localhost:8080/api

logging:
  file: logs/${spring.application.name}.log
  level:
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG
        com.proojec: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE



---

spring:
  profiles: development
  jpa:
    generate-ddl: true
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
      url: jdbc:mysql://192.168.99.100:3306/proojec
      username: root
      password: Irl4nd42014

---

spring:
  profiles: production
  jpa:
    generate-ddl: false
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
      url: jdbc:mysql://localhost:3306/proojec
      username: wordpress
      password: Irl4nd42014